/**
 * Industry verticals knowledge base with SaaS patterns.
 * Each vertical includes market data, pain points, competitors, features, and keywords.
 */

const VERTICALS = {
  "pet grooming": { market: "$14.5B", cagr: "6.2%", pain: "Manual scheduling, no-show clients, paper records", competitors: ["Gingr", "PetExec", "DaySmart Pet"], features: ["online-booking", "client-pet-profiles", "groomer-scheduling", "automated-reminders", "photo-gallery", "loyalty-program", "pos-integration"], keywords: ["pet grooming software", "dog grooming appointment", "pet salon management"] },
  "real estate": { market: "$12.8B", cagr: "12.1%", pain: "Lead management chaos, slow document processing, poor client communication", competitors: ["Follow Up Boss", "kvCORE", "LionDesk"], features: ["crm-leads", "property-listings", "document-automation", "e-signatures", "client-portal", "market-analytics", "commission-tracking"], keywords: ["real estate crm", "property management software", "realtor tools"] },
  "fitness": { market: "$16.4B", cagr: "14.8%", pain: "Class scheduling complexity, membership churn, payment friction", competitors: ["Mindbody", "Glofox", "Wodify"], features: ["class-scheduling", "membership-management", "workout-tracking", "payment-processing", "trainer-portal", "progress-photos", "nutrition-plans"], keywords: ["gym management software", "fitness studio app", "class booking system"] },
  "dental": { market: "$3.7B", cagr: "11.4%", pain: "Insurance claim complexity, appointment no-shows, patient records fragmentation", competitors: ["Dentrix", "Open Dental", "CareStack"], features: ["patient-records", "appointment-scheduling", "insurance-claims", "treatment-plans", "x-ray-storage", "automated-recalls", "billing"], keywords: ["dental practice management", "dentist software", "dental ehr"] },
  "restaurant": { market: "$7.2B", cagr: "15.3%", pain: "Order management, inventory waste, staff scheduling conflicts", competitors: ["Toast", "Square for Restaurants", "Lightspeed"], features: ["pos-system", "online-ordering", "table-management", "inventory-tracking", "staff-scheduling", "menu-builder", "analytics-dashboard"], keywords: ["restaurant management", "pos system", "food ordering software"] },
  "legal": { market: "$1.8B", cagr: "9.7%", pain: "Time tracking inaccuracy, document version chaos, client billing disputes", competitors: ["Clio", "PracticePanther", "MyCase"], features: ["case-management", "time-tracking", "document-management", "client-portal", "billing-invoicing", "calendar-integration", "conflict-checking"], keywords: ["legal practice management", "law firm software", "case management"] },
  "education": { market: "$21.6B", cagr: "18.2%", pain: "Student engagement, progress tracking, administrative overhead", competitors: ["Canvas", "Teachable", "Thinkific"], features: ["course-builder", "student-portal", "progress-tracking", "video-hosting", "quizzes-assessments", "certificates", "payment-subscriptions"], keywords: ["lms software", "online course platform", "education management"] },
  "healthcare": { market: "$28.5B", cagr: "13.6%", pain: "Patient scheduling, EHR complexity, insurance billing errors", competitors: ["Epic", "Athenahealth", "DrChrono"], features: ["ehr-records", "telemedicine", "appointment-scheduling", "insurance-billing", "patient-portal", "prescription-management", "lab-integration"], keywords: ["healthcare software", "ehr system", "telemedicine platform"] },
  "construction": { market: "$10.3B", cagr: "11.8%", pain: "Project delays, budget overruns, subcontractor coordination", competitors: ["Procore", "PlanGrid", "Buildertrend"], features: ["project-management", "budget-tracking", "document-storage", "rfi-management", "daily-logs", "subcontractor-portal", "safety-checklists"], keywords: ["construction management software", "project management", "contractor tools"] },
  "salon": { market: "$1.3B", cagr: "8.5%", pain: "Double bookings, client retention, stylists managing their own books", competitors: ["Vagaro", "Fresha", "Boulevard"], features: ["online-booking", "stylist-calendars", "client-profiles", "automated-reminders", "pos-checkout", "product-inventory", "reviews-integration"], keywords: ["salon software", "hair salon booking", "beauty appointment app"] },
  "accounting": { market: "$18.3B", cagr: "8.6%", pain: "Data entry errors, tax deadline tracking, client document collection", competitors: ["QuickBooks", "Xero", "FreshBooks"], features: ["bookkeeping-automation", "tax-preparation", "invoicing", "expense-tracking", "client-portal", "bank-integration", "financial-reports"], keywords: ["accounting software", "bookkeeping tool", "tax preparation"] },
  "logistics": { market: "$8.9B", cagr: "17.4%", pain: "Route inefficiency, shipment visibility, driver communication gaps", competitors: ["Samsara", "KeepTruckin", "Route4Me"], features: ["route-optimization", "fleet-tracking", "driver-app", "proof-of-delivery", "warehouse-management", "shipment-tracking", "analytics-dashboard"], keywords: ["fleet management", "logistics software", "route planning"] },
  "agriculture": { market: "$4.1B", cagr: "12.9%", pain: "Crop monitoring, weather dependency, supply chain fragmentation", competitors: ["Farmers Edge", "Granular", "Cropio"], features: ["crop-monitoring", "weather-alerts", "inventory-management", "equipment-tracking", "field-mapping", "harvest-planning", "marketplace"], keywords: ["farm management software", "agtech", "precision agriculture"] },
  "recruiting": { market: "$3.2B", cagr: "10.3%", pain: "Resume screening overload, candidate ghosting, slow hiring pipelines", competitors: ["Greenhouse", "Lever", "BambooHR"], features: ["ats-tracking", "resume-parsing", "interview-scheduling", "candidate-pipeline", "job-board-posting", "assessment-tools", "onboarding"], keywords: ["recruiting software", "ats system", "hiring platform"] },
  "event management": { market: "$6.4B", cagr: "11.1%", pain: "Ticket sales complexity, vendor coordination, day-of logistics chaos", competitors: ["Eventbrite", "Cvent", "Bizzabo"], features: ["ticket-sales", "event-page-builder", "vendor-management", "check-in-app", "email-campaigns", "analytics-dashboard", "virtual-event-support"], keywords: ["event management software", "ticketing platform", "event planning tools"] },
  "property management": { market: "$5.6B", cagr: "9.8%", pain: "Rent collection delays, maintenance request chaos, tenant communication", competitors: ["AppFolio", "Buildium", "Rentec Direct"], features: ["rent-collection", "maintenance-requests", "tenant-portal", "lease-management", "accounting", "vacancy-listing", "owner-reports"], keywords: ["property management software", "landlord tools", "rental management"] },
  "veterinary": { market: "$1.9B", cagr: "10.7%", pain: "Patient records scattered, appointment no-shows, inventory management", competitors: ["Cornerstone", "eVetPractice", "Shepherd"], features: ["patient-records", "appointment-scheduling", "prescription-management", "lab-integration", "billing", "client-portal", "inventory-management"], keywords: ["vet practice software", "veterinary management", "animal clinic"] },
  "auto repair": { market: "$2.1B", cagr: "7.9%", pain: "Estimate accuracy, parts ordering, customer updates on repair status", competitors: ["Shop-Ware", "Mitchell 1", "Tekmetric"], features: ["work-orders", "digital-inspections", "parts-catalog", "customer-messaging", "invoicing", "appointment-scheduling", "fleet-accounts"], keywords: ["auto shop software", "repair shop management", "mechanic tools"] },
  "photography": { market: "$0.8B", cagr: "6.1%", pain: "Client gallery management, booking, contract/invoice juggling", competitors: ["HoneyBook", "Studio Ninja", "ShootProof"], features: ["client-galleries", "booking-calendar", "contracts-invoicing", "online-proofing", "workflow-automation", "crm", "questionnaires"], keywords: ["photography business software", "photo gallery client", "photographer crm"] },
  "nonprofit": { market: "$3.4B", cagr: "9.2%", pain: "Donor management, fundraising campaigns, volunteer coordination", competitors: ["Bloomerang", "Little Green Light", "Neon CRM"], features: ["donor-management", "fundraising-campaigns", "volunteer-scheduling", "grant-tracking", "event-management", "email-outreach", "reporting"], keywords: ["nonprofit crm", "fundraising software", "donor management"] },
  "cleaning services": { market: "$2.3B", cagr: "9.5%", pain: "Job scheduling, crew management, customer acquisition", competitors: ["Jobber", "ZenMaid", "Launch27"], features: ["online-booking", "staff-scheduling", "route-optimization", "invoicing", "customer-messaging", "crm", "analytics-dashboard"], keywords: ["cleaning business software", "maid service app", "janitorial management"] },
  "therapy": { market: "$4.8B", cagr: "15.2%", pain: "Session scheduling, insurance billing, secure note-taking", competitors: ["SimplePractice", "TherapyNotes", "Jane App"], features: ["appointment-scheduling", "patient-records", "telemedicine", "insurance-billing", "client-portal", "billing", "progress-tracking"], keywords: ["therapy practice management", "mental health software", "counseling tools"] },
  "church": { market: "$1.1B", cagr: "7.3%", pain: "Member engagement, donation tracking, event coordination", competitors: ["Planning Center", "Breeze", "Pushpay"], features: ["donor-management", "event-management", "volunteer-scheduling", "email-campaigns", "check-in-app", "reporting", "online-booking"], keywords: ["church management software", "church giving", "ministry tools"] },
  "ecommerce": { market: "$25.6B", cagr: "16.8%", pain: "Inventory sync across channels, customer retention, fulfillment complexity", competitors: ["Shopify", "BigCommerce", "WooCommerce"], features: ["inventory-management", "online-ordering", "payment-processing", "analytics-dashboard", "email-campaigns", "crm", "marketplace"], keywords: ["ecommerce platform", "online store builder", "shopping cart software"] },
  "home services": { market: "$3.8B", cagr: "10.1%", pain: "Dispatching, customer communication, seasonal demand fluctuation", competitors: ["ServiceTitan", "Housecall Pro", "Jobber"], features: ["appointment-scheduling", "route-optimization", "invoicing", "customer-messaging", "staff-scheduling", "crm", "analytics-dashboard"], keywords: ["hvac software", "plumbing management", "field service management"] },
  "insurance agency": { market: "$3.5B", cagr: "8.5%", pain: "Manual commission calculations, renewal pipeline falling through cracks, E&O compliance gaps", competitors: ["Applied Epic", "EZLynx", "HawkSoft"], features: ["policy-management", "commission-tracking", "renewal-automation", "carrier-integration", "eo-compliance", "producer-licensing", "document-vault"], keywords: ["insurance agency management software", "ams insurance", "independent agent software"] },
};

const FEATURE_DB = {
  "online-booking": { name: "Online Booking", desc: "Self-serve appointment scheduling with real-time availability", priority: "must", phase: 1, effort: 3 },
  "client-pet-profiles": { name: "Client & Pet Profiles", desc: "Detailed profiles with history, preferences, allergies, photos", priority: "must", phase: 1, effort: 2 },
  "groomer-scheduling": { name: "Staff Scheduling", desc: "Drag-and-drop schedule management with conflict detection", priority: "must", phase: 1, effort: 4 },
  "automated-reminders": { name: "Automated Reminders", desc: "SMS/email reminders to reduce no-shows by up to 40%", priority: "must", phase: 1, effort: 2 },
  "photo-gallery": { name: "Before/After Gallery", desc: "Photo documentation of work with client sharing", priority: "should", phase: 2, effort: 2 },
  "loyalty-program": { name: "Loyalty Program", desc: "Points-based rewards system to boost retention", priority: "nice", phase: 2, effort: 3 },
  "pos-integration": { name: "POS Integration", desc: "Accept payments in-person and online with receipt generation", priority: "must", phase: 1, effort: 4 },
  "crm-leads": { name: "Lead CRM", desc: "Capture, score, and nurture leads through the pipeline", priority: "must", phase: 1, effort: 4 },
  "property-listings": { name: "Property Listings", desc: "MLS-integrated listing management with rich media", priority: "must", phase: 1, effort: 5 },
  "document-automation": { name: "Document Automation", desc: "Auto-generate contracts, disclosures, and forms", priority: "must", phase: 1, effort: 4 },
  "e-signatures": { name: "E-Signatures", desc: "Legally binding electronic signatures on all documents", priority: "must", phase: 1, effort: 3 },
  "client-portal": { name: "Client Portal", desc: "Self-serve portal for documents, status, and communication", priority: "should", phase: 1, effort: 3 },
  "market-analytics": { name: "Market Analytics", desc: "Comparable sales analysis and market trend reports", priority: "should", phase: 2, effort: 5 },
  "commission-tracking": { name: "Commission Tracking", desc: "Automated commission splits and payout calculations", priority: "should", phase: 2, effort: 3 },
  "class-scheduling": { name: "Class Scheduling", desc: "Recurring and drop-in class management with capacity limits", priority: "must", phase: 1, effort: 3 },
  "membership-management": { name: "Membership Management", desc: "Tiered memberships with auto-billing and freeze options", priority: "must", phase: 1, effort: 4 },
  "workout-tracking": { name: "Workout Tracking", desc: "Log exercises, sets, reps with progress visualization", priority: "should", phase: 2, effort: 3 },
  "payment-processing": { name: "Payment Processing", desc: "Stripe/Square integration for subscriptions and one-time payments", priority: "must", phase: 1, effort: 3 },
  "trainer-portal": { name: "Trainer Portal", desc: "Trainers manage their clients, schedules, and programs", priority: "should", phase: 2, effort: 3 },
  "progress-photos": { name: "Progress Photos", desc: "Side-by-side progress photo comparisons", priority: "nice", phase: 2, effort: 2 },
  "nutrition-plans": { name: "Nutrition Plans", desc: "Meal planning with macro tracking and grocery lists", priority: "nice", phase: 2, effort: 4 },
  "patient-records": { name: "Patient Records", desc: "Comprehensive digital health records with history", priority: "must", phase: 1, effort: 5 },
  "appointment-scheduling": { name: "Appointment Scheduling", desc: "Online booking with automated confirmations and reminders", priority: "must", phase: 1, effort: 3 },
  "insurance-claims": { name: "Insurance Claims", desc: "Automated claim submission with status tracking", priority: "must", phase: 1, effort: 5 },
  "treatment-plans": { name: "Treatment Plans", desc: "Visual treatment planning with cost estimates", priority: "must", phase: 1, effort: 4 },
  "x-ray-storage": { name: "X-Ray / Image Storage", desc: "DICOM-compatible image storage and viewer", priority: "should", phase: 1, effort: 4 },
  "automated-recalls": { name: "Automated Recalls", desc: "Smart recall system for overdue appointments", priority: "should", phase: 2, effort: 2 },
  "billing": { name: "Billing & Invoicing", desc: "Generate invoices, process payments, handle insurance", priority: "must", phase: 1, effort: 4 },
  "pos-system": { name: "POS System", desc: "Touchscreen point-of-sale with order management", priority: "must", phase: 1, effort: 5 },
  "online-ordering": { name: "Online Ordering", desc: "Branded web/app ordering with delivery integration", priority: "must", phase: 1, effort: 4 },
  "table-management": { name: "Table Management", desc: "Floor plan editor with real-time table status", priority: "must", phase: 1, effort: 3 },
  "inventory-tracking": { name: "Inventory Tracking", desc: "Real-time stock levels with auto-reorder alerts", priority: "must", phase: 1, effort: 4 },
  "staff-scheduling": { name: "Staff Scheduling", desc: "Shift management with availability and swap requests", priority: "should", phase: 1, effort: 3 },
  "menu-builder": { name: "Menu Builder", desc: "Visual menu editor with pricing, photos, and modifiers", priority: "must", phase: 1, effort: 3 },
  "analytics-dashboard": { name: "Analytics Dashboard", desc: "Revenue, orders, and operational KPIs at a glance", priority: "should", phase: 2, effort: 3 },
  "case-management": { name: "Case Management", desc: "Full case lifecycle tracking with documents and deadlines", priority: "must", phase: 1, effort: 5 },
  "time-tracking": { name: "Time Tracking", desc: "Automatic timer with manual entry and billing rates", priority: "must", phase: 1, effort: 3 },
  "document-management": { name: "Document Management", desc: "Version-controlled document storage with search", priority: "must", phase: 1, effort: 4 },
  "billing-invoicing": { name: "Billing & Invoicing", desc: "Time-based billing with trust account management", priority: "must", phase: 1, effort: 4 },
  "calendar-integration": { name: "Calendar Integration", desc: "Two-way sync with Google/Outlook calendars", priority: "should", phase: 1, effort: 2 },
  "conflict-checking": { name: "Conflict Checking", desc: "Automated conflict of interest screening", priority: "must", phase: 1, effort: 3 },
  "course-builder": { name: "Course Builder", desc: "Drag-and-drop curriculum with modules and lessons", priority: "must", phase: 1, effort: 4 },
  "student-portal": { name: "Student Portal", desc: "Personalized dashboard with progress and assignments", priority: "must", phase: 1, effort: 3 },
  "progress-tracking": { name: "Progress Tracking", desc: "Learning analytics with completion rates and scores", priority: "must", phase: 1, effort: 3 },
  "video-hosting": { name: "Video Hosting", desc: "Built-in video player with DRM protection", priority: "must", phase: 1, effort: 4 },
  "quizzes-assessments": { name: "Quizzes & Assessments", desc: "Multiple question types with auto-grading", priority: "should", phase: 1, effort: 3 },
  "certificates": { name: "Certificates", desc: "Custom completion certificates with verification", priority: "should", phase: 2, effort: 2 },
  "payment-subscriptions": { name: "Payment & Subscriptions", desc: "Course sales, bundles, and recurring subscriptions", priority: "must", phase: 1, effort: 3 },
  "ehr-records": { name: "EHR Records", desc: "HIPAA-compliant electronic health records", priority: "must", phase: 1, effort: 5 },
  "telemedicine": { name: "Telemedicine", desc: "Video consultations with waiting room and notes", priority: "must", phase: 1, effort: 4 },
  "insurance-billing": { name: "Insurance Billing", desc: "Automated insurance claim processing", priority: "must", phase: 1, effort: 5 },
  "patient-portal": { name: "Patient Portal", desc: "Self-serve access to records, bills, and messaging", priority: "should", phase: 1, effort: 3 },
  "prescription-management": { name: "Prescription Management", desc: "E-prescribing with pharmacy integration", priority: "must", phase: 1, effort: 4 },
  "lab-integration": { name: "Lab Integration", desc: "Order labs and receive results electronically", priority: "should", phase: 2, effort: 4 },
  "project-management": { name: "Project Management", desc: "Gantt charts, milestones, and task assignments", priority: "must", phase: 1, effort: 5 },
  "budget-tracking": { name: "Budget Tracking", desc: "Real-time cost tracking vs estimates with change orders", priority: "must", phase: 1, effort: 4 },
  "document-storage": { name: "Document Storage", desc: "Centralized plans, permits, and contracts", priority: "must", phase: 1, effort: 3 },
  "rfi-management": { name: "RFI Management", desc: "Submit, track, and respond to information requests", priority: "should", phase: 1, effort: 3 },
  "daily-logs": { name: "Daily Logs", desc: "Photo-documented daily progress reports", priority: "should", phase: 1, effort: 2 },
  "subcontractor-portal": { name: "Subcontractor Portal", desc: "Bids, schedules, and document sharing with subs", priority: "should", phase: 2, effort: 3 },
  "safety-checklists": { name: "Safety Checklists", desc: "OSHA-aligned safety inspections with photo evidence", priority: "should", phase: 2, effort: 2 },
  "stylist-calendars": { name: "Stylist Calendars", desc: "Individual calendars with service duration and breaks", priority: "must", phase: 1, effort: 3 },
  "client-profiles": { name: "Client Profiles", desc: "Preferences, history, photos, and notes", priority: "must", phase: 1, effort: 2 },
  "pos-checkout": { name: "POS Checkout", desc: "In-store payment with tips and product sales", priority: "must", phase: 1, effort: 4 },
  "product-inventory": { name: "Product Inventory", desc: "Retail product stock tracking with reorder alerts", priority: "should", phase: 2, effort: 3 },
  "reviews-integration": { name: "Reviews Integration", desc: "Automated review requests after appointments", priority: "should", phase: 2, effort: 2 },
  "bookkeeping-automation": { name: "Bookkeeping Automation", desc: "AI categorization of transactions with bank feeds", priority: "must", phase: 1, effort: 5 },
  "tax-preparation": { name: "Tax Preparation", desc: "Tax form generation with filing integration", priority: "must", phase: 1, effort: 5 },
  "invoicing": { name: "Invoicing", desc: "Professional invoices with online payment links", priority: "must", phase: 1, effort: 3 },
  "expense-tracking": { name: "Expense Tracking", desc: "Receipt scanning and mileage tracking", priority: "must", phase: 1, effort: 3 },
  "bank-integration": { name: "Bank Integration", desc: "Live bank feed with reconciliation", priority: "must", phase: 1, effort: 4 },
  "financial-reports": { name: "Financial Reports", desc: "P&L, balance sheet, cash flow with custom reports", priority: "must", phase: 1, effort: 4 },
  "route-optimization": { name: "Route Optimization", desc: "AI-powered multi-stop route planning saving 20%+ fuel", priority: "must", phase: 1, effort: 5 },
  "fleet-tracking": { name: "Fleet Tracking", desc: "Real-time GPS tracking of all vehicles", priority: "must", phase: 1, effort: 4 },
  "driver-app": { name: "Driver App", desc: "Mobile app for drivers with navigation and tasks", priority: "must", phase: 1, effort: 4 },
  "proof-of-delivery": { name: "Proof of Delivery", desc: "Photo/signature capture at delivery point", priority: "must", phase: 1, effort: 2 },
  "warehouse-management": { name: "Warehouse Management", desc: "Inventory locations, picking lists, and stock transfers", priority: "should", phase: 2, effort: 4 },
  "shipment-tracking": { name: "Shipment Tracking", desc: "Customer-facing tracking page with real-time updates", priority: "should", phase: 1, effort: 3 },
  "crop-monitoring": { name: "Crop Monitoring", desc: "Satellite and sensor-based crop health tracking", priority: "must", phase: 1, effort: 5 },
  "weather-alerts": { name: "Weather Alerts", desc: "Hyper-local weather forecasts and frost/storm alerts", priority: "must", phase: 1, effort: 3 },
  "inventory-management": { name: "Inventory Management", desc: "Seed, fertilizer, and equipment inventory tracking", priority: "must", phase: 1, effort: 3 },
  "equipment-tracking": { name: "Equipment Tracking", desc: "GPS location and maintenance schedules for equipment", priority: "should", phase: 2, effort: 3 },
  "field-mapping": { name: "Field Mapping", desc: "GPS-based field boundary mapping with zone management", priority: "must", phase: 1, effort: 4 },
  "harvest-planning": { name: "Harvest Planning", desc: "Yield estimation and harvest scheduling", priority: "should", phase: 2, effort: 3 },
  "marketplace": { name: "Marketplace", desc: "Direct-to-buyer marketplace for produce", priority: "nice", phase: 2, effort: 5 },
  "ats-tracking": { name: "ATS Tracking", desc: "Kanban-style candidate pipeline management", priority: "must", phase: 1, effort: 4 },
  "resume-parsing": { name: "Resume Parsing", desc: "AI-powered resume extraction and scoring", priority: "must", phase: 1, effort: 4 },
  "interview-scheduling": { name: "Interview Scheduling", desc: "Calendar integration with candidate self-booking", priority: "must", phase: 1, effort: 3 },
  "candidate-pipeline": { name: "Candidate Pipeline", desc: "Visual pipeline with stage automation", priority: "must", phase: 1, effort: 3 },
  "job-board-posting": { name: "Job Board Posting", desc: "One-click posting to Indeed, LinkedIn, etc.", priority: "should", phase: 1, effort: 3 },
  "assessment-tools": { name: "Assessment Tools", desc: "Skills tests and coding challenges", priority: "should", phase: 2, effort: 4 },
  "onboarding": { name: "Onboarding", desc: "New hire checklist and document collection", priority: "should", phase: 2, effort: 3 },
  "ticket-sales": { name: "Ticket Sales", desc: "Online ticket sales with seating and tier options", priority: "must", phase: 1, effort: 4 },
  "event-page-builder": { name: "Event Page Builder", desc: "Branded event landing pages with RSVP", priority: "must", phase: 1, effort: 3 },
  "vendor-management": { name: "Vendor Management", desc: "Vendor directory with contracts and communication", priority: "should", phase: 1, effort: 3 },
  "check-in-app": { name: "Check-in App", desc: "QR code scanning for fast event check-in", priority: "must", phase: 1, effort: 2 },
  "email-campaigns": { name: "Email Campaigns", desc: "Pre/post event email sequences", priority: "should", phase: 2, effort: 3 },
  "virtual-event-support": { name: "Virtual Event Support", desc: "Live streaming and virtual booths", priority: "nice", phase: 2, effort: 5 },
  "rent-collection": { name: "Rent Collection", desc: "Online rent payments with ACH and auto-pay", priority: "must", phase: 1, effort: 3 },
  "maintenance-requests": { name: "Maintenance Requests", desc: "Tenant-submitted requests with photo upload and tracking", priority: "must", phase: 1, effort: 3 },
  "tenant-portal": { name: "Tenant Portal", desc: "Self-serve portal for payments, requests, and documents", priority: "must", phase: 1, effort: 3 },
  "lease-management": { name: "Lease Management", desc: "Digital leases with e-sign and renewal tracking", priority: "must", phase: 1, effort: 4 },
  "accounting": { name: "Accounting", desc: "Property-level income/expense tracking and reporting", priority: "must", phase: 1, effort: 4 },
  "vacancy-listing": { name: "Vacancy Listing", desc: "Syndicate listings to Zillow, Apartments.com, etc.", priority: "should", phase: 2, effort: 3 },
  "owner-reports": { name: "Owner Reports", desc: "Automated monthly financial reports for property owners", priority: "should", phase: 2, effort: 3 },
  "work-orders": { name: "Work Orders", desc: "Digital work orders with parts and labor tracking", priority: "must", phase: 1, effort: 3 },
  "digital-inspections": { name: "Digital Inspections", desc: "Photo/video vehicle inspections with customer sharing", priority: "must", phase: 1, effort: 3 },
  "parts-catalog": { name: "Parts Catalog", desc: "Integrated parts lookup with pricing and availability", priority: "should", phase: 1, effort: 4 },
  "customer-messaging": { name: "Customer Messaging", desc: "SMS/email updates on repair status", priority: "must", phase: 1, effort: 2 },
  "fleet-accounts": { name: "Fleet Accounts", desc: "Manage fleet clients with custom pricing", priority: "nice", phase: 2, effort: 3 },
  "client-galleries": { name: "Client Galleries", desc: "Password-protected photo galleries with download", priority: "must", phase: 1, effort: 3 },
  "booking-calendar": { name: "Booking Calendar", desc: "Online booking with package selection", priority: "must", phase: 1, effort: 3 },
  "contracts-invoicing": { name: "Contracts & Invoicing", desc: "Digital contracts with e-sign and payment integration", priority: "must", phase: 1, effort: 4 },
  "online-proofing": { name: "Online Proofing", desc: "Client photo selection with favorites and comments", priority: "must", phase: 1, effort: 3 },
  "workflow-automation": { name: "Workflow Automation", desc: "Automated emails, tasks, and reminders per project stage", priority: "should", phase: 2, effort: 3 },
  "crm": { name: "CRM", desc: "Client relationship management with tags and notes", priority: "should", phase: 1, effort: 3 },
  "questionnaires": { name: "Questionnaires", desc: "Pre-shoot questionnaires to understand client vision", priority: "nice", phase: 2, effort: 2 },
  "donor-management": { name: "Donor Management", desc: "Donor profiles with giving history and engagement", priority: "must", phase: 1, effort: 4 },
  "policy-management": { name: "Policy Management", desc: "Full policy lifecycle tracking — quotes, binds, endorsements, cancellations — in one place", priority: "must", phase: 1, effort: 5 },
  "renewal-automation": { name: "Renewal Automation", desc: "Automated renewal pipeline with 90/60/30-day alerts and one-click re-quote across carriers", priority: "must", phase: 1, effort: 3 },
  "carrier-integration": { name: "Carrier Integration", desc: "Real-time bi-directional data feeds with 300+ carriers for policy downloads and e-docs", priority: "must", phase: 1, effort: 5 },
  "eo-compliance": { name: "E&O Compliance", desc: "Automated audit trails, required-field enforcement, and timestamped client communication logs", priority: "must", phase: 1, effort: 4 },
  "producer-licensing": { name: "Producer Licensing", desc: "Track agent license expiry, CE credits, and appointment status by state with auto-alerts", priority: "should", phase: 1, effort: 3 },
  "document-vault": { name: "Document Vault", desc: "Secure client-facing portal for policy docs, ID cards, and certificates of insurance", priority: "should", phase: 2, effort: 3 },
  "fundraising-campaigns": { name: "Fundraising Campaigns", desc: "Online donation pages with goals and progress", priority: "must", phase: 1, effort: 3 },
  "volunteer-scheduling": { name: "Volunteer Scheduling", desc: "Volunteer sign-ups with shift management", priority: "must", phase: 1, effort: 3 },
  "grant-tracking": { name: "Grant Tracking", desc: "Application deadlines, requirements, and reporting", priority: "should", phase: 1, effort: 3 },
  "event-management": { name: "Event Management", desc: "Fundraising events with ticket sales and sponsorships", priority: "should", phase: 2, effort: 3 },
  "email-outreach": { name: "Email Outreach", desc: "Donor communication with segmentation and automation", priority: "should", phase: 2, effort: 3 },
  "reporting": { name: "Reporting", desc: "Donor retention, campaign ROI, and board reports", priority: "should", phase: 2, effort: 3 },
};

const TECH_STACKS = {
  bootstrap: { frontend: "React + Tailwind CSS", backend: "Firebase (Serverless)", db: "Firestore", hosting: "Firebase Hosting", auth: "Firebase Auth", payments: "Stripe", extras: ["Vercel (alt)", "SendGrid (email)"] },
  seed: { frontend: "Next.js + Tailwind CSS", backend: "Node.js + Express", db: "PostgreSQL (Supabase)", hosting: "Vercel / Railway", auth: "NextAuth.js", payments: "Stripe", extras: ["Redis (cache)", "Resend (email)", "S3 (storage)"] },
  funded: { frontend: "Next.js + Tailwind + Storybook", backend: "Node.js + tRPC / NestJS", db: "PostgreSQL + Redis", hosting: "AWS / GCP", auth: "Clerk / Auth0", payments: "Stripe + ACH", extras: ["Sentry (monitoring)", "Datadog (APM)", "Terraform (IaC)"] },
  enterprise: { frontend: "React / Next.js + Design System", backend: "Microservices (Go/Node)", db: "PostgreSQL + Redis + Elasticsearch", hosting: "Kubernetes (GKE/EKS)", auth: "Okta / Auth0 Enterprise", payments: "Stripe + Invoice + ACH", extras: ["Datadog", "PagerDuty", "Terraform", "ArgoCD"] },
};

const PRICING_TEMPLATES = {
  bootstrap: [
    { name: "Free", price: "$0", period: "/forever", features: ["Up to 50 records", "Basic features", "Community support", "1 user"], cta: "Get Started" },
    { name: "Pro", price: "$29", period: "/month", features: ["Unlimited records", "All features", "Email support", "Up to 5 users", "API access"], cta: "Start Free Trial", highlighted: true },
    { name: "Business", price: "$79", period: "/month", features: ["Everything in Pro", "Priority support", "Custom branding", "Unlimited users", "Advanced analytics"], cta: "Contact Sales" },
  ],
  seed: [
    { name: "Starter", price: "$0", period: "/forever", features: ["Up to 100 records", "Core features", "Email support", "2 users"], cta: "Start Free" },
    { name: "Professional", price: "$49", period: "/month", features: ["Up to 5,000 records", "All features", "Priority support", "10 users", "API access", "Integrations"], cta: "Start Free Trial", highlighted: true },
    { name: "Business", price: "$149", period: "/month", features: ["Unlimited records", "All features", "Phone support", "Unlimited users", "SSO", "Custom reports"], cta: "Start Free Trial" },
    { name: "Enterprise", price: "Custom", period: "", features: ["Everything in Business", "Dedicated support", "SLA guarantee", "On-premise option", "Custom integrations"], cta: "Contact Sales" },
  ],
  funded: [
    { name: "Free", price: "$0", period: "/forever", features: ["Limited usage", "Core features", "Docs only", "1 user"], cta: "Get Started" },
    { name: "Team", price: "$79", period: "/user/mo", features: ["Full features", "Priority support", "10 users", "API access", "Integrations", "Analytics"], cta: "Start Free Trial", highlighted: true },
    { name: "Business", price: "$199", period: "/user/mo", features: ["Everything in Team", "SSO/SAML", "Audit logs", "SLA", "Unlimited users", "Dedicated CSM"], cta: "Start Free Trial" },
    { name: "Enterprise", price: "Custom", period: "", features: ["Everything in Business", "On-premise", "Custom SLA", "Professional services", "Dedicated infrastructure"], cta: "Contact Sales" },
  ],
  enterprise: [
    { name: "Team", price: "$149", period: "/user/mo", features: ["Full platform", "Priority support", "SSO", "API access", "Integrations"], cta: "Request Demo" },
    { name: "Enterprise", price: "Custom", period: "", features: ["Everything in Team", "On-premise", "Custom SLA", "Dedicated infrastructure", "Professional services", "24/7 support"], cta: "Contact Sales", highlighted: true },
  ],
};

module.exports = { VERTICALS, FEATURE_DB, TECH_STACKS, PRICING_TEMPLATES };
